# Generated by Django 5.0.4 on 2024-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('taste', models.CharField(max_length=30)),
                ('whatsnew', models.CharField(max_length=30)),
                ('changes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('mainarea', models.CharField(max_length=20)),
                ('subarea', models.IntegerField()),
                ('streetno', models.CharField(max_length=30)),
                ('flavour', models.CharField(max_length=20)),
                ('topping', models.IntegerField()),
                ('instructions', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='foz',
        ),
    ]
